version: '3.8'

services:
  search-engine-es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - search-engine-network
  
  search-engine-kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    environment:
      ELASTICSEARCH_HOSTS: '["http://search-engine-es01:9200"]'
    ports:
      - "5601:5601"
    depends_on:
      - search-engine-es01
    networks:
      - search-engine-network

  search-engine-app:
    cpus: 1
    mem_limit: 1000m
    container_name: search-engine-app
    networks:
      - search-engine-network
    build:
      dockerfile: ./.infra/Dockerfile
      context: .
    ports:
      - 3000:3000
    depends_on:
      - search-engine-es01
      - search-engine-kibana

volumes:
  data01:

networks:
  search-engine-network:
    driver: bridge